steps:
  # Paso 0: Construir la imagen de Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--platform=linux/amd64'
      - '-t'
      - 'gcr.io/$PROJECT_ID/image_juan'
      - '.'

  # Paso 1: Etiquetar la imagen
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/image_juan', 'gcr.io/$PROJECT_ID/image_juan']

  # Paso 2: Subir la imagen a Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/image_juan']

  # Paso 3: Desplegar en Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Obtener el usuario actual
        current_user=$(gcloud config get-value account)

        # Imprimir el usuario actual
        echo "Usuario desplegando: $current_user"

  # Paso 4: Desplegar en Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'app-flask'
      - '--image=gcr.io/test-docker-416523/image_juan'
      - '--platform=managed'
      - '--region=us-central1'
